[tool.poetry]
name = "tour_guide_bot"
version = "0.0.1"
description = ""
authors = ["Andrey Yantsen <andrey@janzen.su>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = {version = "*", allow-prereleases = true}
Babel = "^2.10.3"
SQLAlchemy = {extras = ["asyncio", "aiomysql", "aiosqlite", "postgresql_asyncpg"], version = "^1.4.40"}
alembic = "^1.8.1"
greenlet = "*"
psycopg2-binary = "^2.9.3"
dateparser = "^1.1.1"
ffmpeg-python = "^0.2.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.7.0"

[tool.poetry.scripts]
bot = 'tour_guide_bot.cli:run'

[build-system]
requires = ["setuptools >= 40.6.0", "wheel", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
