[tool.poetry]
name = "tour_guide_bot"
version = "0.0.1"
description = ""
authors = ["Andrey Yantsen <andrey@janzen.su>"]
license = "Apache-2.0"

[tool.isort]
profile = "black"
force_sort_within_sections = true
known_first_party = [
    "tour_guide_bot",
]
forced_separate = []
combine_as_imports = true

[tool.black]
target-version = ["py310"]

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = {version = "*", allow-prereleases = true, extras = ["job-queue"]}
Babel = "^2.11.0"
SQLAlchemy = {extras = ["asyncio", "aiomysql", "aiosqlite", "postgresql_asyncpg"], version = "^1.4.44"}
alembic = "^1.8.1"
greenlet = "*"
psycopg2-binary = "^2.9.5"
dateparser = "^1.1.4"
ffmpeg-python = "^0.2.0"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
isort = "^5.11.1"

[tool.poetry.scripts]
bot = 'tour_guide_bot.cli:run'

[build-system]
requires = ["setuptools >= 40.6.0", "wheel", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
