[tool.poetry]
name = "tour_guide_bot"
version = "0.0.1"
description = ""
authors = ["Andrey Yantsen <andrey@janzen.su>"]
license = "Apache-2.0"

[tool.isort]
profile = "black"
force_sort_within_sections = true
known_first_party = [
    "tour_guide_bot",
]
forced_separate = []
combine_as_imports = true

[tool.black]
target-version = ["py310"]

[tool.poetry.dependencies]
python = "^3.10 <3.12"
python-telegram-bot = {version = "^20.3", allow-prereleases = true, extras = ["job-queue"]}
Babel = "^2.12.1"
SQLAlchemy = {extras = ["asyncio", "aiomysql", "aiosqlite", "postgresql_asyncpg"], version = "^2.0.15"}
alembic = "^1.11.1"
greenlet = "*"
psycopg2-binary = "^2.9.6"
dateparser = "^1.1.8"
ffmpeg-python = "^0.2.0"
aiohttp = "^3.8.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
isort = "^5.12.0"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.0.0"
ruff = "^0.0.269"
telethon = "^1.28.5"
pytest-mock = "^3.10.0"

[tool.poetry.scripts]
bot = 'tour_guide_bot.cli:run'

[build-system]
requires = ["setuptools >= 40.6.0", "wheel", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    # Warning from past/builtins/misc, which out of our control
    "ignore:the imp module is deprecated in favour of importlib:DeprecationWarning",
    "ignore:'imghdr' is deprecated and slated for removal:DeprecationWarning",
]
markers = [
    "enabled_languages",
    "approved_tour_ids",
    "tours",
    "skip_payment_token_stub",
]
asyncio_mode = "auto"

[tool.ruff]
ignore = ["E", "I"]
