"""Add a title for the sections

Revision ID: 4c08132e37ab
Revises: dd186ed90dec
Create Date: 2022-08-14 17:29:36.292424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c08132e37ab'
down_revision = 'dd186ed90dec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_section', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_section', 'title')
    # ### end Alembic commands ###
