"""Initial schema

Revision ID: a975b155ed1b
Revises: 
Create Date: 2022-07-29 10:41:44.721580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a975b155ed1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('permissions', sa.Enum('full', name='adminpermissions'), nullable=True),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_phone'), 'admin', ['phone'], unique=True)
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_phone'), 'guest', ['phone'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.Enum('welcome_message', name='key'), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bought_tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.Column('expire_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bought_tours_guest_id'), 'bought_tours', ['guest_id'], unique=False)
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_translation_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tour_translation_id'], ['tour_translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_section')
    op.drop_table('tour_translation')
    op.drop_table('telegram_user')
    op.drop_index(op.f('ix_bought_tours_guest_id'), table_name='bought_tours')
    op.drop_table('bought_tours')
    op.drop_table('tour')
    op.drop_table('settings')
    op.drop_index(op.f('ix_guest_phone'), table_name='guest')
    op.drop_table('guest')
    op.drop_index(op.f('ix_admin_phone'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
