"""Remove language from admin/guest

Revision ID: d237f493ca8f
Revises: 2661986786cd
Create Date: 2022-08-03 20:31:35.043749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd237f493ca8f'
down_revision = '2661986786cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'language')
    op.drop_column('guest', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('language', sa.VARCHAR(), nullable=True))
    op.add_column('admin', sa.Column('language', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
