"""Add index on is_user_notified column in bought_tours

Revision ID: 2661986786cd
Revises: 4658f3573fbe
Create Date: 2022-07-31 19:04:14.077952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2661986786cd'
down_revision = '4658f3573fbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bought_tours_is_user_notified'), 'bought_tours', ['is_user_notified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bought_tours_is_user_notified'), table_name='bought_tours')
    # ### end Alembic commands ###
