"""Add is_user_notified column for bought_tours

Revision ID: 4658f3573fbe
Revises: d84b9ed34ee5
Create Date: 2022-07-31 17:17:16.413002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4658f3573fbe'
down_revision = 'd84b9ed34ee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bought_tours', sa.Column('is_user_notified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bought_tours', 'is_user_notified')
    # ### end Alembic commands ###
